Authentication – Refresh, persistence & API
quran/quran-ios pull request #681
Opened 2024-12-31 21:05 UTC by mohannad-hassan

2025-01-03 00:20 UTC, mohamede1945 requested changes
Jazak Allah khair, Mohannad!  

I believe we need to refine the design of a few components to make them more reusable and minimize the chances of failure. Let me know if you have any questions or need clarification.  

Thank you!

2025-01-03 00:20 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/Persistance.swift
> +protocol Persistance {
I suggest creating a general `SecurePersistence` API (under Core/ directory) rather than one specifically for authentication.  

A recommended pattern can be seen in [this directory](https://github.com/quran/quran-ios/tree/3d34dadc1fb260e035b23649fd28f5b06a22f6b0/Core/Preferences), where `Preferences` is implemented as a service, and consumers define `PreferenceKey` objects to describe the data that needs to be persisted. I think we can do something similar with `SecurePersistence` and `SecurePersistenceKey`.

Also please add a couple of tests for this class.

2025-01-03 00:20 UTC, mohamede1945 commented on Data/AuthenticationClient/Tests/AuthentincationDataManagerTests.swift
> +        persistance = PersistanceMock()
I recommend minimizing the use of mocks, as they can make tests more dependent on the mock behavior than the actual application code. Instead, I recommend focusing on mocking only the third-party API for authentication and avoid creating mocks for the code we own. This approach ensures tests remain closely aligned with the application's real behavior.

2025-01-03 00:20 UTC, mohamede1945 commented on Data/AuthenticationClient/Tests/AuthentincationDataManagerTests.swift
> +        }
Use AsyncAssertThrows

2025-01-03 00:20 UTC, mohamede1945 commented on Data/AuthenticationClient/Tests/AuthentincationDataManagerTests.swift
> +        }
The do-catch is not needed. XCTest will fail the test if an except is thrown. Same in other tests below

2025-01-04 14:59 UTC, mohannad-hassan commented on Data/AuthenticationClient/Sources/AuthentincationDataManager.swift
> +//  AuthentincationDataManager.swift
Resorted to `client`. I see that nothing under Data is named "Service", and that it's a common name for the classes in domain.

2025-01-04 16:58 UTC, mohannad-hassan commented on Data/AuthenticationClient/Sources/AuthentincationDataManagerImpl.swift
> +            }.store(in: &cancellables)
Good observation.

2025-01-04 18:50 UTC, mohannad-hassan commented on Data/AuthenticationClient/Tests/AuthentincationDataManagerTests.swift
> +        persistance = PersistanceMock()
I'm actually of the opinion that one should _avoid_ mocking 3rd party code. Not often that these would be open for subclassing or easy for subclassing. The class `OIDAuthState` of the library we're using proved to be so. It was open, but I'd have to mock four other types. Same issue prevented from stubbing it.  

Moreover, wrapping 3rd party code under abstractions allows to define the interactions between the main logic and the kind of responsibility we seek from the 3rd party code. In other words, we're adapting the 3rd party code to our needs - as much as the situation allows without awkward design.

2025-01-04 19:40 UTC, mohannad-hassan commented on Data/AuthenticationClient/Tests/AuthentincationDataManagerTests.swift
> +        persistance = PersistanceMock()
As for depending on mocks, I understand that this is a concern, however, I try to counter that by keeping mocks as small as possible, and relying only on providing ready responses (call succeeds or fails, call returns something, ...)  

I use the term 'mock' liberally, what I usually use are mostly stubs and spies. 

I expounded on that, because these are key techniques I use (dealing with 3rd party and testing doubles strategies.) We can discuss that face-to-face if there's something to be aligned.

2025-01-04 21:34 UTC, mohannad-hassan commented on Data/AuthenticationClient/Sources/AuthenticationData.swift
> +}
This was supposed to be a protocol, but turned it into a class (similarly to Java's abstract classes.) The reason for this is the need for `Codable` conformance while also using the type `AuthenticationData` as an existential type. 

However, I did experiment with it now, and it seems it can be used as an existential type. I'll be updating this.

2025-01-04 22:10 UTC, mohannad-hassan commented on Data/AuthenticationClient/Sources/AuthenticationData.swift
> +}
BTW, I thought of extracting the OAuth wrappers (caller and data) out to a `Core` package, but these library-specific design discrepancies discouraged me from that.

2025-01-04 22:45 UTC, mohannad-hassan commented on Data/AuthenticationClient/Sources/AuthentincationDataManager.swift
> +    func restoreState() async throws -> Bool
Perhaps naming needs to be reconsidered. The purpose of this is to restore and reevaluate the status. The full picture of this API is to be used by sync logic. 

But your intuition is on point: this part is still not clear. The main remaining point is synchronization especially on startup, as this API is intended to be the base for that.

2025-01-05 15:59 UTC, mohannad-hassan commented on Data/AuthenticationClient/Sources/AuthentincationDataManager.swift
>      func set(appConfiguration: OAuthAppConfiguration)
Okay then, I moved setting the configurations to the initialization. However, I'm still not comfortable to make it nullable. 

As explained in the PR's description: _The public state of the client needs to indicate two non-usable states (not-configured and not-authenticate), so I saw that it's better to unify access through a non-optional type for both of them._

2025-01-05 21:12 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/AuthentincationDataManager.swift
>      func set(appConfiguration: OAuthAppConfiguration)
> The public state of the client needs to indicate two non-usable states (not-configured and not-authenticate)

Do you mind explaining why is that please?

2025-01-05 21:20 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/AuthentincationDataManager.swift
> +    func restoreState() async throws -> Bool
What I’ve observed in other auth libraries is that they typically provide functionality to check `isAuthenticated` and perform `login`, similar to your implementation. In addition to that they often include either an explicit `start` method or implicitly initiate the auth process during the initialization of the service/client class. So, that would be my recommendation.

2025-01-05 21:25 UTC, mohannad-hassan commented on Data/AuthenticationClient/Sources/AuthentincationDataManager.swift
>      func set(appConfiguration: OAuthAppConfiguration)
Services using the client need to guard against the state of not being authenticated. They also need to guard against the case of the client not having been configured (if cloned by someone.) These are the two non-usable states of the client. 

The client needs to expose the first state, so my first idea is to unify all states of the client (not-configured, non-authenticated & authenticated) through the `authenticationState` property. I favoured this over handling one state through nil checking and the other through a property.

2025-01-05 21:28 UTC, mohannad-hassan commented on Data/AuthenticationClient/Sources/AuthentincationDataManager.swift
>      func set(appConfiguration: OAuthAppConfiguration)
To be honest, a lot of the vagueness here will be cleared once we get to integrating the new APIs along the normal flow.

2025-01-05 21:31 UTC, mohamede1945 commented on Data/AuthenticationClient/Tests/AuthentincationDataManagerTests.swift
> +        persistance = PersistanceMock()
Apologies, I’m not sure I fully understand your point. You mentioned wanting to avoid mocking but also referred to implementing small mocks. 

To clarify my perspective: tests should avoid using mocks/fakes/spies/stubs unless absolutely necessary. These cases include scenarios where the actual dependency cannot be used in tests (e.g., backend APIs or time-based APIs) or where using a mock provides a significant benefit (e.g., file system operations that could slow tests due to extensive reading and writing). 

If a mock is needed, it should be added to the following directory: [Core/SystemDependencies](https://github.com/quran/quran-ios/tree/main/Core/SystemDependencies). Additionally, a corresponding fake implementation should be placed in: [Core/SystemDependenciesFake](https://github.com/quran/quran-ios/tree/main/Core/SystemDependenciesFake). This approach ensures that we explicitly allowlist the APIs for which their actual implementation cannot be used.

2025-01-05 21:40 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/AuthentincationDataManager.swift
>      func set(appConfiguration: OAuthAppConfiguration)
In general, a client instance should be configured for a consumer to use it. If the consumer does not configure the client, no client will be available for use. A null client serves as a clear indication that the app is not configured for authentication. This approach aligns with best practices followed by many system APIs, where the API is configured during initialization to ensure it can be used effectively.

There are additional nuances to consider, such as handling invalid configurations. Ideally, verifying the configuration during initialization would be great, but I assume this isn't feasible due to the need for backend API requests. Therefore, late verification of the configuration is acceptable. However, when early validation is possible, we should prioritize it and not defer it.

2025-01-05 21:43 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/AuthentincationDataManager.swift
> +//  AuthentincationDataManager.swift
Yeah Client works too. Thank you!

2025-01-05 21:57 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/AuthenticationData.swift
> +}
I believe using a protocol is a positive step forward. However, the current API and implementation handle multiple responsibilities, and I’d suggest breaking them up for better separation of concerns:

1. **Data Handling:** Managing the data, including serialization and deserialization.  
2. **State Change Listening:** Listening to `OIDAuthStateChangeDelegate` changes and notifying consumers.  
3. **Action Encapsulation:** Encapsulating actions that can be performed by `OIDAuthState`.

My suggestion is to separate the first responsibility from the second and third. For example:

1. Introduce an `AuthState` **struct** to handle serialization and deserialization of state details.  
2. Create an `AuthStateService` that listens for state changes and provides APIs such as `refreshToken` and `isAuthorized`. 

This approach ensures a cleaner design by dividing responsibilities across focused components.

2025-01-05 21:59 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/AuthenticationData.swift
> +}
I also recognize that the library's API might be awkward at times, making it challenging to provide a more refined solution. However, I truly appreciate your patience and effort in overcoming these obstacles. 

Thank you so much for your hard work, Mohannad!

2025-01-05 22:06 UTC, mohannad-hassan commented on Data/AuthenticationClient/Tests/AuthentincationDataManagerTests.swift
> +        persistance = PersistanceMock()
> You mentioned wanting to avoid mocking but also referred to implementing small mocks. 
I avoid mocking 3rd party code; in our case, that would be keychain access functions and the AppAuth-iOS library. My solution for this would be wrapping such code behind an abstraction and providing a mock that extends that. 

> tests should avoid using mocks/fakes/spies/stubs unless absolutely necessary 
I see. I largely agree. I usually mock things that represent complex logic and I'd think of mocking first for cross-package/cross-layer dependencies. But since this is the practice we're taking here, I'll adjust it. 

For our case though, we have:
- Keychain access, wrapped by `Persistence`. I can see this fits well with SystemDependencies. 
- The OAuth library, wrapped by `OAuthCaller`. Do you that sitting there?

2025-01-10 20:13 UTC, mohannad-hassan commented
@mohamede1945 
Here's an update: 
- The most noticeable update is the redesign of the OAuth client part, that is used by `AuthenticationClient`. The `OAuthService` is now responsible for executing actions and _updating state_. The new data, or `OAuthStateData` should be a simple struct now. 
- Extracted that part to a separate Core module. However, I'd like your input if anything is missing from the current mocks to be the kind of fakes we're using, before this is extracted out.
- Didn't extract `Persistence` out. It's now an internal type, so the API is fitted for that. I preferred not to put time into making it more general. Let me know what you think. 

There is one or two points that I've put off for now: 
- Defining an enum for the available scopes Quran.com has. 
- Currently, OAuth-flow errors revert the client to a non-authenticated state. It might be needed to differentiate server failures and networking issues and other classes. I think it'll be better, in terms of its UX, not to request the user to login again in the first case.

2025-01-19 21:55 UTC, mohamede1945 requested changes
Jazak Allah khyran for the changes. This looks so great mashaa'Allah, just a couple more more changes and we should be good to merge inshaa'Allah.

2025-01-19 21:55 UTC, mohamede1945 commented on Core/OAuthService/OAuthService.swift
> +    func refreshIfNeeded(data: OAuthStateData) async throws -> OAuthStateData
nit: Can we rename refreshIfNeeded to refreshAccessTokenIfNeeded to make it clearer please.

2025-01-19 21:55 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/AppAuthOAuthService.swift
> +        let serviceConfiguration = try await discoverConfiguration(forIssuer: appConfigurations.authorizationIssuerURL)
Can we move this line to the AuthenticationClient and keep this implementation just a wrapper around 3p library.

2025-01-19 21:55 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/Persistence.swift
> +    func retrieve() throws -> Data?
To make this generic:

1. I think we need to make this keyed persistence to allow saving and retrieving different kind of information.
2. Can we move it under Core/ as a separate target please?

2025-01-19 21:55 UTC, mohamede1945 commented on Data/AuthenticationClient/Tests/AuthenticationClientTests.swift
> +private final class OAuthServiceMock: OAuthService {
Let's move this to Core because we will need to use it in more tests as we integrate auth with other features.

2025-01-19 21:55 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/AppAuthOAuthService.swift
> +//
Since this is an implementation of Core/OAuthService. Can we have it under maybe Core/OAuthServiceImpl target?

2025-01-19 21:55 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/AuthenticationClient.swift
> +    func restoreState() async throws -> Bool
I'd use `AuthenticationState` rather than bool.

2025-01-19 21:55 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/AuthenticationClient.swift
> +}
I'm not sure why would we need to use this over just AuthenticationClientImpl's initializer.

2025-01-19 21:55 UTC, mohamede1945 commented on Data/AuthenticationClient/Tests/AuthenticationClientTests.swift
> +private struct OauthStateEncoderMock: OAuthStateDataEncoder {
I don't think we need this. I think we can use the real implementation.

2025-01-19 21:55 UTC, mohamede1945 commented on Data/AuthenticationClient/Tests/AuthenticationClientTests.swift
> +private final class AutehenticationDataMock: Equatable, Codable, OAuthStateData {
Same here, can we get rid of this please?

2025-01-19 21:55 UTC, mohamede1945 commented on Data/AuthenticationClient/Tests/AuthenticationClientTests.swift
> +private final class PersistenceMock: Persistence {
Same for this mock as well.

2025-01-20 14:32 UTC, mohannad-hassan commented on Core/OAuthService/OAuthService.swift
> +    func refreshIfNeeded(data: OAuthStateData) async throws -> OAuthStateData
Sounds about right. That's basically the gist of the underlying data.

2025-01-20 14:33 UTC, mohannad-hassan commented on Data/AuthenticationClient/Sources/AppAuthOAuthService.swift
> +        let serviceConfiguration = try await discoverConfiguration(forIssuer: appConfigurations.authorizationIssuerURL)
Good point. I missed this when I extracted the package out.

2025-01-20 15:18 UTC, mohannad-hassan commented on Data/AuthenticationClient/Tests/AuthenticationClientTests.swift
> +private struct OauthStateEncoderMock: OAuthStateDataEncoder {
The encoder is tied to the `OAuthStateData` implementation. `AppAuthStateData` encapsulates an instance of `OIDAuthState` that is not easy to control for tests.

2025-01-20 16:09 UTC, mohannad-hassan commented on Data/AuthenticationClient/Sources/AuthenticationClient.swift
> +}
Sort of my habit: builders go hand in hand with protocols. Also, I was anticipating some logic before I made the client take non-nil configurations.

2025-01-20 23:24 UTC, mohamede1945 commented on Data/AuthenticationClient/Tests/AuthenticationClientTests.swift
> +private final class AutehenticationDataMock: Equatable, Codable, OAuthStateData {
Oh I see. Can we move the encode and decode methods to OAuthStateData protocol then? Something like:

```swift
public protocol OAuthStateData {
    func init(_ data: Data) throws
    func encode(_ data: OAuthStateData) throws -> Data
    ...
}
```

WDYT?

2025-01-22 22:03 UTC, mohannad-hassan commented on Data/AuthenticationClient/Tests/AuthenticationClientTests.swift
> +private final class AutehenticationDataMock: Equatable, Codable, OAuthStateData {
We'll need to avoid hardcoding the concrete type, since `AuthenticationClient` is responsible for persisting the data.  If we go by the suggestion, it'll be something like this: 

```swift
public protocol OAuthStateData {
    func init(_ data: Data) throws
    func encode(_ data: OAuthStateData) throws -> Data
}

public protocol OAuthService {
    /// Concrete type can be accessed here but still abstracted. 
    static var stateDataType: OAuthStateData.Type { get }
    // ... 
}

func persistencePoint() {
     // How it'd be invoked. 
     let stateData = try currentAuthClient.Self.stateDataType.init(encodedData)
}
```

Honestly, I would only go for meta types in a generic function/class, so that's why I didn't think of this. 

This is more concise than using a separate encoder, but I think the encoder is simpler. So what do you think? @mohamede1945

2025-01-23 00:27 UTC, mohamede1945 approved these changes
Thanks Mohannad a lot for such wonderful work.

2025-01-23 00:27 UTC, mohamede1945 commented on Core/OAuthService/OAuthService.swift
> +public struct OAuthServiceConfiguration {
I don't think this needs to be part of the API, does it?

2025-01-23 00:27 UTC, mohamede1945 commented on Core/SystemDependencies/KeychainAccess.swift
> +public protocol KeychainAccess {
This is perfect! Thank you so much

2025-01-23 00:27 UTC, mohamede1945 commented on Data/AuthenticationClient/Sources/AuthentincationClientImpl.swift
> +    // Noticeably,
Could you please explain why is that?

2025-01-23 00:27 UTC, mohamede1945 commented on Example/QuranEngineApp/Classes/Container.swift
>      }()
nit: This could be simply equals nil and remove the Constant.QuranOAuthAppConfigurations.

2025-01-23 00:27 UTC, mohamede1945 commented on Package.swift
> +        target(type, name: "AppAuthOAuthService", hasTests: false, dependencies: [
I would prefer naming this target OAuthServiceImpl or something similar, similar to how you named the fake to make it easy to find the API and both implementations.

2025-01-23 05:19 UTC, mohannad-hassan commented on Core/OAuthService/OAuthService.swift
> +public struct OAuthServiceConfiguration {
It's practically a Parameters Object.

2025-01-23 05:26 UTC, mohannad-hassan commented on Data/AuthenticationClient/Sources/AuthentincationClientImpl.swift
> +    // Noticeably,
Forgot to complete the comment. Will commit it. Here it is: 

Noticeably, AuthenticationClient may accept an enum defining the available services. The client may request offline access and profile scopes by default. The OAuth service would still only accept String scopes.

On another hand, the issuer host is probably going to be the API host. We may see how the relationship pans out.

2025-01-23 06:10 UTC, mohannad-hassan commented on Example/QuranEngineApp/Classes/Container.swift
>      }()
I meant to leave the constants to be filled if any developer of a forked repo wanted to add their own OAuth account.

2025-01-23 06:15 UTC, mohannad-hassan commented on Data/AuthenticationClient/Sources/AuthentincationClientImpl.swift
> +    // Noticeably,
This is also meant to support forked apps. The OAuth account used by the apps is going to be automatically granted the requested scopes. 

I don't plan to put much effort in supporting this. I may just expose a property that returns the granted scopes.

2025-01-23 06:31 UTC, mohannad-hassan commented on Package.swift
> +        target(type, name: "AppAuthOAuthService", hasTests: false, dependencies: [
Okay, but I'll keep the `AppAuth`, as `OAuthServiceAppAuthImpl`.

2025-01-25 17:34 UTC, mohamede1945 commented on Data/AuthenticationClient/Tests/AuthenticationClientTests.swift
> +private final class AutehenticationDataMock: Equatable, Codable, OAuthStateData {
Sounds good, yeah let's keep it.

2025-01-25 17:49 UTC, mohamede1945 approved these changes

2025-01-25 17:49 UTC, mohamede1945 commented on Core/SystemDependenciesFake/SecurityAccessFake.swift
> +public class SecurityAccessFake: KeychainAccess {
Could you please rename it to KeychainAccessFake?

2025-01-25 19:47 UTC, merged